{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: publicdb
spec:
  ports:
  - name: '5432'
    port: 5432
  selector:
    app: publicdb
  {{ if .Values.enableLoadBalancer }}
  type: LoadBalancer
  {{ if .Values.loadBalancerIP }}
  loadBalancerIP: {{ .Values.loadBalancerIP | quote }}
  {{ end }}
  {{ end }}
{{ end }}
