language: bash
sudo: required
env:
  matrix:
  - DEPLOY_ENVIRONMENT=production DEPLOY_BRANCH=master
#  - DEPLOY_ENVIRONMENT=production DEPLOY_TAGS=true
services:
- docker
script:
- |
  if [ "${DEPLOY_ENVIRONMENT}" != "" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ] &&\
     ( \
      ([ "${TRAVIS_BRANCH}" == "${DEPLOY_BRANCH}" ] && ! echo "${TRAVIS_COMMIT_MESSAGE}" | grep -- --no-deploy) ||\
      ([ "${DEPLOY_TAGS}" == "true" ] && [ "${TRAVIS_TAG}" != "" ]) \
     )
  then
      openssl aes-256-cbc -K $encrypted_2cdba463b699_key -iv $encrypted_2cdba463b699_iv -in ./k8s-ops-secret.json.enc -out secret-k8s-ops.json -d
      K8S_ENVIRONMENT_NAME="${DEPLOY_ENVIRONMENT}"
      OPS_REPO_SLUG="OriHoch/knesset-data-k8s"
      OPS_REPO_BRANCH="${DEPLOY_BRANCH}"
      wget https://raw.githubusercontent.com/OriHoch/sk8s-ops/master/run_docker_ops.sh
      chmod +x run_docker_ops.sh
      if ./run_docker_ops.sh "${K8S_ENVIRONMENT_NAME}" "
         RES=0;
         ! ./helm_upgrade_external_chart.sh pipelines-jobs --force && echo 'failed pipelines-jobs upgrade' && RES=1;
         exit "'$'"RES
      " "orihoch/sk8s-ops" "${OPS_REPO_SLUG}" "${OPS_REPO_BRANCH}"; then
        true
      else
        echo "failed to run docker ops"
        false
      fi
  else
    echo "skipping deployment"
    true
  fi
