{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: metrics-influxdb
spec:
  selector:
    app: metrics-influxdb
  ports:
  - name: "8086"
    port: 8086
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics-influxdb
spec:
  replicas: 1
  strategy: {type: "Recreate"}
  template:
    metadata:
      labels:
        app: metrics-influxdb
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - image: influxdb
        name: influxdb
        ports:
        - containerPort: 8086
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
{{ end }}
