apiVersion: v1
kind: ConfigMap
metadata:
  name: people-nginx
data:
  default.conf: |
    server {
      listen 8000;
      location /pipelines/data/ {
        root /;
        autoindex on;
      }
    }
