apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: frontend
        image: {{ .Values.frontendImage }}
        resources: {{ .Values.frontendResources | toYaml | nindent 10 }}
        command:
          - /bin/bash
          - -c
          - |
            sed -i 's|worker_processes  auto|worker_processes 4|' /etc/nginx/nginx.conf
            exec /docker-entrypoint.sh nginx -g 'daemon off;'
