{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: {{.Values.replicas | default "1"}}
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        # update the pod on nginx-conf changes
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        command:
          - /bin/sh
          - -c
          - |
            sed -i 's|worker_processes  auto|worker_processes 4|' /etc/nginx/nginx.conf
            exec /docker-entrypoint.sh nginx -g 'daemon off;'
        ports:
        - containerPort: 80
        resources: {"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"cpu": "78m", "memory": "256Mi"}}
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
          readOnly: true
        {{ if .Values.htpasswdSecretName }}
        - name: nginx-htpasswd
          mountPath: /etc/nginx/htpasswd
          readOnly: true
        {{ end }}
        - name: pipelines-data
          mountPath: /pipelines/data
          subPath: data
          readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      {{ if .Values.htpasswdSecretName }}
      - name: nginx-htpasswd
        secret:
          secretName: {{ .Values.htpasswdSecretName }}
      {{ end }}
      - name: pipelines-data
        persistentVolumeClaim:
          claimName: data2
{{ end }}
