{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: {{.Values.replicas | default "1"}}
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        # update the pod on nginx-conf changes
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources: {"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"cpu": "78m", "memory": "256Mi"}}
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
          readOnly: true
        {{ if .Values.htpasswdSecretName }}
        - name: nginx-htpasswd
          mountPath: /etc/nginx/htpasswd
          readOnly: true
        {{ end }}
        {{- if .Values.pipelinesDataNfsServer }}
        - name: pipelines-data
          mountPath: /pipelines/data
          subPath: data
          readOnly: true
        {{- else if .Values.pipelinesDataPvcName }}
        - name: pipelines-data
          mountPath: /pipelines/data
          subPath: data
          readOnly: true
        {{- end }}
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      {{ if .Values.htpasswdSecretName }}
      - name: nginx-htpasswd
        secret:
          secretName: {{ .Values.htpasswdSecretName }}
      {{ end }}
        {{- if .Values.pipelinesDataNfsServer }}
        - name: pipelines-data
          nfs:
            server: {{ .Values.pipelinesDataNfsServer }}
            path: {{ .Values.pipelinesDataNfsServerPath | default "/" | quote }}
        {{- else if .Values.pipelinesDataPvcName }}
        - name: pipelines-data
          persistentVolumeClaim:
            claimName: {{ .Values.pipelinesDataPvcName }}
        {{- end }}
{{ end }}
