{{ if .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{ if .Values.ingress.tls }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  {{ end }}
  name: nginx
  namespace: oknesset
spec:
  rules:
  {{ range .Values.ingress.hostnames }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
  {{ end }}
  {{ if .Values.ingress.tls }}
  tls:
  - hosts:
    {{ range .Values.ingress.hostnames }}
    - {{ . }}
    {{ end }}
    secretName: nginx-cert
  {{ end }}
{{ end }}
