#
# committee-build-meetings
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-committee-build-meetings-envfrom
data:
  PIPELINES_SCRIPT: |
    cd /pipelines &&\
    dpp run ./download &&\
    dpp run ./join-meetings &&\
    dpp run ./download_members &&\
    dpp run ./build &&\
    rm -rf /pipelines/data/* &&\
    mv /pipelines/dist /pipelines/data/
---
{{ dict "name" "pipeline-committee-build-meetings" "Values" .Values "enabled" .Values.committeesBuildMeetings.enabled "image" .Values.committeesImage | include "pipeline-job" }}
