#
# committee-build-meetings
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-committee-build-meetings-envfrom
data:
  PIPELINES_SCRIPT: |
    cd /pipelines && (source ./pipelines_script.sh) && (
      rm -rf /pipelines/data/*
      mv /pipelines/dist /pipelines/data/
      exit 0
    )
---
{{ dict "name" "pipeline-committee-build-meetings" "Values" .Values "enabled" .Values.committeesBuildMeetings.enabled "image" .Values.committeesImage | include "pipeline-job" }}
