{{ if and .Values.enabled .Values.committeesEnabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pipelines-committees
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pipelines-committees
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: pipelines
        image: {{ .Values.committeesImage | quote }}
        env:
        - name: DISABLE_MEMBER_PERCENTS
          value: {{ .Values.committees_DISABLE_MEMBER_PERCENTS | default "" | quote }}
        command:
        - sh
        - "/dpp/docker/run.sh"
        - server
        ports:
        - containerPort: 5000
        resources: {{ .Values.committeesResources }}
        volumeMounts:
        - name: k8s-ops
          mountPath: /secret_service_key
          subPath: secret.json
          readOnly: true
        - mountPath: /pipelines/data
          name: data
          subPath: data
        - mountPath: /pipelines/dist
          name: data
          subPath: dist
        - mountPath: /var/redis
          name: data
          subPath: redis
      volumes:
      - name: k8s-ops
        secret:
          secretName: ops
      - name: data
        gcePersistentDisk:
          pdName: {{ .Values.committeesPersistentDiskName | quote }}
{{ end }}
