#
# committee-protocols
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-committee-protocols-ops-envfrom
data:
  INITIAL_SYNC_SCRIPT: |
    mkdir -p /pipelines/data/committees/kns_documentcommitteesession &&\
    gsutil -m rsync -r gs://knesset-data-pipelines/data/committees/kns_documentcommitteesession/ /pipelines/data/committees/kns_documentcommitteesession/
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-committee-protocols-envfrom
data:
  PIPELINES_SCRIPT: |
    cd /pipelines &&\
    (
      RES=0;

      ! run_pipeline ./committees/download_document_committee_session && RES=1;
      ! run_pipeline ./committees/parse_meeting_protocols_text && RES=1;
      ! run_pipeline ./committees/parse_meeting_protocols_parts && RES=1;

      rm -rf /pipelines/data/committees/kns_documentcommitteesession;
      exit $RES
    )
  CHECK_REMOTE_STORAGE: https://storage.googleapis.com/knesset-data-pipelines/data/committees/download_document_committee_session/
---
{{ dict "name" "pipeline-committee-protocols" "Values" .Values "enabled" .Values.committeesProtocols.enabled "opsEnvFrom" true "enableProxy" true | include "pipeline-job" }}
