apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-dataservices1-envfrom
data:
  PIPELINES_BATCH_NAME: dataservices1
---
{{ dict "name" "pipeline-dataservices1" "Values" .Values "enabled" .Values.dataservices.enabled "enableProxy" true | include "pipeline-job" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-dataservices2-envfrom
data:
  PIPELINES_BATCH_NAME: dataservices2
---
{{ dict "name" "pipeline-dataservices2" "Values" .Values "enabled" .Values.dataservices.enabled "enableProxy" true | include "pipeline-job" }}
