{{ if and .Values.enabled .Values.enableNfs }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nfs
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs
    spec:
      containers:
      - name: nfs
        image: k8s.gcr.io/volume-nfs:0.8
        resources: {"requests": {"cpu": "60m", "memory": "100Mi"}}
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: exports
      volumes:
        - name: exports
          {{ if .Values.nfsGcePersistentDiskName }}
          persistentVolumeClaim:
            claimName: oknesset-nfs-gcepd
          {{ else }}
          emptyDir: {}
          {{ end }}
{{ end }}
