{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: committees-pipelines-nginx
data:
  default.conf: |
    server {
      listen 8000;
      error_page 404 =200 @homepageredirect;
      rewrite ^/member/([0-9]*)/ /members/$1.html last;
      location / {
        root /pipelines/dist/;
      }
      location @homepageredirect {
        return 302 https://{{ .Values.committeesDomain | default "oknesset.org" }}/index.html;
      }
    }
{{ end }}
