apiVersion: v1
kind: Service
metadata:
  name: committees-pipelines
spec:
  ports:
  - name: '5000'
    port: 5000
  - name: '8000'
    port: 8000
  - name: '8080'
    port: 8080
  selector:
    app: committees-pipelines
