apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  selector:
    matchLabels:
      app: airflow-scheduler
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      nodeSelector:
        # This node label is updated by apps/openbus/bin/update_node_allowed_ips.py script
        oknesset-allowed-ip: "true"
      terminationGracePeriodSeconds: 240
      containers:
        - name: scheduler
          image: {{ .Values.airflowImage }}
          resources: {{ .Values.airflowScheduler.resources }}
          env:
            - name: KNESSET_DATA_PIPELINES_AIRFLOW_ROLE
              value: "scheduler"
            - name: KNESSET_DATA_PIPELINES_AIRFLOW_INITIALIZE
              value: "yes"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom: {"secretKeyRef":{"name":"airflow-db", "key":"SQLALCHEMY_URL"}}
            {{ if .Values.airflow.enableEmails }}
            - name: AIRFLOW__EMAIL__EMAIL_BACKEND
              value: "airflow.utils.email.send_email_smtp"
            - name: AIRFLOW__SMTP__SMTP_HOST
              valueFrom: {"secretKeyRef": {"name": "airflow-email", "key": "AIRFLOW__SMTP__SMTP_HOST" }}
            - name: AIRFLOW__SMTP__SMTP_MAIL_FROM
              value: {{ .Values.airflow.AIRFLOW__SMTP__SMTP_MAIL_FROM }}
            - name: AIRFLOW__SMTP__SMTP_USER
              valueFrom: {"secretKeyRef": {"name": "airflow-email", "key": "AIRFLOW__SMTP__SMTP_USER" }}
            - name: AIRFLOW__SMTP__SMTP_PASSWORD
              valueFrom: {"secretKeyRef": {"name": "airflow-email", "key": "AIRFLOW__SMTP__SMTP_PASSWORD" }}
            {{ end }}
            {{ if .Values.airflow.AIRFLOW__WEBSERVER__BASE_URL }}
            - name: AIRFLOW__WEBSERVER__BASE_URL
              value: {{ .Values.airflow.AIRFLOW__WEBSERVER__BASE_URL | quote }}
            {{ end }}
            - name: PGSQL_HOST
              value: "publicdb"
            - name: PGSQL_USER
              value: "postgres"
            - name: PGSQL_PASSWORD
              valueFrom: {"secretKeyRef": {"name": "publicdb", "key": "POSTGRES_PASSWORD" }}
            - name: PGSQL_PORT
              value: "5432"
            - name: PGSQL_DB
              value: "postgres"
            - name: KNESSET_PIPELINES_DATA_PATH
              value: "/data"
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: "True"
            - name: GOOGLE_CLOUD_PROJECT
              value: "hasadna-oknesset"
            - name: KNESSET_DATA_PIPELINES_AIRFLOW_ADMIN_PASSWORD
              valueFrom: {"secretKeyRef": {"name": "airflow", "key": "admin_password" }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/airflow-google-service-account/key.json"
          volumeMounts:
            - name: airflow-home
              mountPath: /var/airflow
            - name: data
              mountPath: /data
            - name: airflow-secret
              subPath: google-service-account-key-json
              mountPath: /var/airflow-google-service-account/key.json
      volumes:
        - name: airflow-home
          nfs:
            server: {{ .Values.nfsServer | quote }}
            path: {{ .Values.airflow.homeNfsPath | quote }}
        - name: data
          nfs:
            server: {{ .Values.nfsServer | quote }}
            path: {{ .Values.nfsServerPath }}
        - name: airflow-secret
          secret:
              secretName: airflow
