apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-scheduler
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-scheduler
subjects:
- kind: ServiceAccount
  name: airflow-scheduler
