apiVersion: v1
kind: Service
metadata:
  name: dante-socks-proxy
spec:
  type: NodePort
  selector:
    app: dante-socks-proxy
  ports:
  - name: "1080"
    port: 1080
    nodePort: {{ .Values.danteNodePort }}
