apiVersion: apps/v1
kind: Deployment
metadata:
  name: dante-socks-proxy
spec:
  selector:
    matchLabels:
      app: dante-socks-proxy
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: dante-socks-proxy
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: dante
          # built from pipelines/dante
          image: orihoch/dante@sha256:1c2c0ace870d621e62b9cd48437c0120e7d9a0ecd34c50da6e02cf2877096444
          resources: {"requests": {"cpu": "20m", "memory": "100Mi"}, "limits": {"cpu": "20m", "memory": "100Mi"}}
          command:
            - danted
            - -f
            - /etc/dante/dante.conf
          env:
            - name: DANTE_USER
              valueFrom:
                secretKeyRef:
                  name: dante-conf
                  key: username
            - name: DANTE_PASS
              valueFrom:
                secretKeyRef:
                  name: dante-conf
                  key: password
