{{ if and .Values.enabled .Values.enableTika }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
spec:
  selector:
    matchLabels:
      app: tika
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tika
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: tika
        image: logicalspark/docker-tikaserver
        resources: {"requests": {"cpu": "1", "memory": "1Gi"}, "limits": {"cpu": "2", "memory": "2Gi"}}
        ports:
        - containerPort: 9998
{{ end }}
