{{ if .Values.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      include /etc/nginx/conf.d/healthcheck.inc;

      {{ if .Values.metrics.enabled }}
      location /grafana/ {
        proxy_pass http://metrics-grafana:3000/;
        include /etc/nginx/conf.d/restricted.inc;
      }
      {{ end }}

      {{ if .Values.pipelines.enabled }}
      location /pipelines/data/ {
        proxy_pass http://pipelines:8000/pipelines/data/;
      }
      location /pipelines/ {
        proxy_pass http://pipelines:5000/;
      }
      {{ end }}

      {{ if .Values.people.enabled }}
      location /people/data/ {
        proxy_pass http://people:8000/pipelines/data/;
      }
      location /people/pipelines/ {
        proxy_pass http://people:5000/;
      }
      {{ end }}

      {{ if .Values.committees.enabled }}
      location /committees/data/ {
        proxy_pass http://committees-pipelines:8080/pipelines/data/;
      }
      location /committees/dist/ {
        proxy_pass http://committees-pipelines:8080/pipelines/dist/;
      }
      location /committees/pipelines/ {
        proxy_pass http://committees-pipelines:5000/;
      }
      {{ end }}
    }

  healthcheck.inc: |
    location = / {
        return 200 'it works!';
        add_header Content-Type text/plain;
    }

  restricted.inc: |
    {{ if .Values.nginx.htpasswdSecretName }}
    auth_basic "Restricted Content";
    auth_basic_user_file /etc/nginx/htpasswd/secret-nginx-htpasswd;
    {{ else }}
    {{ if .Values.traefik.enabled }}
      ERROR!! CANNOT ENABLE TRAEFIK WITHOUT AUTHENTICATION!
    {{ end }}
    {{ end }}

{{ end }}
