{{ if .Values.traefik.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-traefik
data:
  traefik.toml: |
    # https://docs.traefik.io/configuration/commons/

    debug = false

    defaultEntryPoints = ["http", "https"]
    
    [entryPoints]
        [entryPoints.http]
          address = ":80"
          {{ if .Values.traefik.acmeEmail }}
            [entryPoints.http.redirect]
              entryPoint = "https"
          {{ end }}

        {{ if .Values.traefik.acmeEmail }}
        [entryPoints.https]
          address = ":443"
            [entryPoints.https.tls]
        {{ end }}

    {{ if .Values.traefik.acmeEmail }}
    # let's encrypt automatic ssl certificate issue and renewal
    [acme]
      email = {{ .Values.traefik.acmeEmail | quote }}
      {{ if .Values.traefik.dnsProvider }}
      dnsProvider = {{ .Values.traefik.dnsProvider | quote }}
      {{ end }}
      storage = "/traefik-acme/acme.json"
      entryPoint = "https"
{{ .Values.traefik.acmeDomains | indent 6 }}
    {{ end }}

    [file]
    
    [backends]
      {{ if .Values.nginx.enabled }}
      [backends.nginx]
        [backends.nginx.servers.server1]
          url = "http://nginx:80"
      {{ end }}

    [frontends]
      {{ if .Values.nginx.enabled }}
      [frontends.default]
        backend="nginx"
        passHostHeader = true
      {{ end }}

{{ end }}
