pipelines-jobs:
  committeesImage: gcr.io/hasadna-oknesset/knesset-data-committees-cd:4457e9fa50884d29443a37fd079d6aac34425dfa
  image: orihoch/knesset-data-pipelines:add-metrics-2
  peopleImage: gcr.io/hasadna-oknesset/knesset-data-people-cd:3a514f24726d66a7ed14c1948575dfa4267cbb59
revolving-doors:
  pipelinesImage: gcr.io/hasadna-oknesset/revolving-doors-cd:40e82c595397ac96cd3da4d63a0ffee272141e9a
