pipelines-jobs:
  committeesImage: gcr.io/hasadna-oknesset/knesset-data-committees-cd:922fdc1d072ad45b3a1b58079e08a6d03b9fd4d3
  image: gcr.io/hasadna-oknesset/knesset-data-pipelines-cd:e71fe0097f9cc4967c8f07ac7877affae8994738
