global:
  enableRootChart: true
  environmentName: production

pipelines-jobs:
  enabled: true
  image: orihoch/knesset-data-pipelines:sk8s-pipelines-v0.0.3-g
  committeesImage: orihoch/knesset-data-committees:v0.0.1-c-sk8s-g

  # main dataservice and related downloads
  dataservices: {"enabled": true}

  # download and parse committee protocols
  committeesProtocols: {"enabled": true}
  committeesProtocolsParse: {"enabled": true}

  # build the meetings html pages
  committeesBuildMeetings: {"enabled": true}

metrics:
  enabled: true
