pipelines-jobs:
  committeesImage: gcr.io/hasadna-oknesset/knesset-data-committees-cd:0516598a4954557906ebebf6044fbb25a705016c
  image: orihoch/knesset-data-pipelines:additional-tables-runner-improvements-2
  peopleImage: orihoch/knesset-data-people:dump-to-storage-4
revolving-doors:
  pipelinesImage: gcr.io/hasadna-oknesset/revolving-doors-cd:40e82c595397ac96cd3da4d63a0ffee272141e9a
