global:
  enableRootChart: true
  environmentName: production
  googleProjectId: hasadna-oknesset
  backupsBucketName: oknesset-k8s-backups
  publicdbSecret: publicdb

pipelines-jobs:
  enabled: true
  image: orihoch/knesset-data-pipelines:additional-tables
  committeesImage: orihoch/knesset-data-committees:v0.0.1-d
  peopleImage: orihoch/knesset-data-people

  # main dataservice and related downloads
  dataservices: {"enabled": false}

  # download and parse committee protocols
  committeesProtocols: {"enabled": false}
  committeesPackage: {"enabled": false}

  # build the meetings html pages
  committeesBuildMeetings: {"enabled": false}

  # publish data externally (e.g. to re:dash)
  datapublishers: {"enabled": false}

  people: {"enabled": false}

  serverEnabled: true
  protocolsEnabled: true
  pipelinesEnabled: true
  peopleEnabled: true

metrics:
  enabled: false
  GF_SERVER_DOMAIN: production.oknesset.org

nginx:
  enabled: true
  enablePipelineDashboard: true
  mainDomain: production.oknesset.org
  htpasswdSecretName: nginx-htpasswd

traefik:
  enabled: true
  acmeDomains: |
    [[acme.domains]]
      main = "production.oknesset.org"
    [[acme.domains]]
      main = "committees-next.oknesset.org"
  acmeEmail: ori@uumpa.com
  dnsProvider: route53
  # AWS IAM user name = oknesset-route53-api
  # kubectl create secret generic route53 --from-literal=AWS_SECRET_ACCESS_KEY=***
  AWS_ACCESS_KEY_ID: AKIAIWMQWDTIM7IZS3EA
  AWS_REGION: "eu-west-1"
  # gcloud compute addresses create oknesset-production-traefik --region=us-central1
  # gcloud compute addresses describe oknesset-production-traefik --region=us-central1 | grep ^address:
  loadBalancerIP: "35.184.112.37"
  enableLoadBalancer: true
  enableCommitteesNext: true
  committeesNextDomain: committees-next.oknesset.org


committees-next:
  enabled: true

publicdb:
  enabled: true
  resources: >
    {"requests": {"cpu": "200m", "memory": "400Mi"}, "limits": {"cpu": "300m", "memory": "1500Mi"}}
  adminerEnabled: true
  enableLoadBalancer: true
  # gcloud --project=hasadna-oknesset compute addresses create oknesset-production-publicdb --region=us-central1
  # gcloud --project=hasadna-oknesset compute addresses describe oknesset-production-publicdb --region=us-central1 | grep ^address:
  loadBalancerIP: "35.184.9.19"
