metrics:
  enabled: false
  GF_SERVER_DOMAIN: production.oknesset.org

nginx:
  enabled: true
  htpasswdSecretName: nginx-htpasswd
  enableMetrics: false
  enablePipelines: true

pipelines:
  enabled: true
  DISABLE_MEMBER_PERCENTS: "yes"
  persistentDiskName: oknesset-pipelines
  image: orihoch/knesset-data-pipelines
  committeesDomain: oknesset.org

publicdb:
  enabled: true
  resources: >
    {"requests": {"cpu": "200m", "memory": "500Mi"}, "limits": {"memory": "2Gi"}}
  adminerEnabled: true
  # enableLoadBalancer: true
  # gcloud --project=hasadna-oknesset compute addresses create oknesset-production-publicdb --region=us-central1
  # gcloud --project=hasadna-oknesset compute addresses describe oknesset-production-publicdb --region=us-central1 | grep ^address:
  # loadBalancerIP: "35.184.9.19"
  # gcloud --project=hasadna-oknesset compute disks create --size=100GB --zone=us-central1-a publicdb
  persistentDiskName: oknesset-publicdb
  # kubectl create secret generic redash-reader --from-literal=REDASH_READER_PASSWORD=***
  redashReaderSecret: redash-reader
  secretName: publicdb
  nodeSelector: 'oknesset-postgres: "true"'
  # kubectl get nodes -l oknesset-postgres=true -o 'jsonpath={.items[0].status.addresses[?(@.type=='"'"'ExternalIP'"'"')].address}'
  enableHostPort: true
