airflowImage: ghcr.io/hasadna/knesset-data-pipelines/knesset-data-pipelines-airflow:bd79196c75744e1f171dbb25c6b8942276734bce
image: ghcr.io/hasadna/knesset-data-pipelines/knesset-data-pipelines-legacy:bd79196c75744e1f171dbb25c6b8942276734bce
