airflowImage: ghcr.io/hasadna/knesset-data-pipelines/knesset-data-pipelines-airflow:f588f602914896f9dc6ab05e01511b88b534ca83
image: ghcr.io/hasadna/knesset-data-pipelines/knesset-data-pipelines-legacy:f588f602914896f9dc6ab05e01511b88b534ca83
