airflowImage: ghcr.io/hasadna/knesset-data-pipelines/knesset-data-pipelines-airflow:b75d53eef63b972faf8ee3d68422eb5b033202b5
image: ghcr.io/hasadna/knesset-data-pipelines/knesset-data-pipelines-legacy:b75d53eef63b972faf8ee3d68422eb5b033202b5
