apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-run
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pipeline-run
rules:
- apiGroups: [""]
  resources: ["pods", "deployments"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-run
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-run
subjects:
- kind: ServiceAccount
  name: pipeline-run
